[package]
name = "twt_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
chronographer = { path = "/Users/abhishekshivale/Developer/ChronoGrapher/core" }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
groqai = "0.1.10"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1"
rand = "0.8"
dotenvy = "0.15"